---
title: |
  Encode-Decoder \
  Models
format:
  revealjs:
    width: 1200
    scrollable: true
    include-in-header: "math.html"
    footer: m408.inqs.info/lectures/11a
    theme: [default, styles.scss]
    preview-links: true
    navigation-mode: vertical
    controls-layout: edges
    controls-tutorial: true
    slide-number: true
    pointer:
      pointerSize: 48
    incremental: false 
    chalkboard:
      theme: whiteboard
      chalk-width: 4
knitr:
  opts_chunk: 
    echo: true
    eval: false
    message: false
    warnings: false
    comment: "#>" 
    
revealjs-plugins:
  - pointer
  
filters: 
  - reveal-auto-agenda

editor: source
---

## Translation

How do we translate the following phrase to a different language?


::: {.fragment}

All models are wrong, some are useful.

:::


## Example Translations

Todos los modelos son incorrectos, algunos son útiles.

## Protein Sequences


::: {.columns}

::: {.column}

### Amino Acid Sequences

AASAHFTGCPWVURDYU

:::

::: {.column}

### Structures

- Secondary Structures Structures
    - $\alpha$-helices
    - $\beta$-sheets
- Tertiary Structures
    - Structures


:::

:::

## Translations

How would a computer translate for one sequence to another?

What are the important things that a computer must know?


## Encoder-Decoder Models

Encoder-Decoder models is designed to take in a sequence, conduct mathematical functions, and transform it to a new sequence. Commonly known as [seq2seq](https://en.wikipedia.org/wiki/Seq2seq) problems.

## Encoder

- The **Encoder** component is designed to handle the input sequence and model it with numerical values.

- The numerical values are stored in both long-term and short-term memories, LSTM cells.

## Decoder

- The **Decoder** component takes the inputs from the long-term and short-term memory of the encoder component and inputs it into a new LSTM cell

- The LSTM cell will then predict the first value (word) of a sequence.

- The word perdicted will then be used for a new LSTM cell to predict the next word.

- The process continues until an `<EOS>` token (end of sequence) is produced.

## StatQuest

[Youtube Video](https://youtu.be/L8HKweZIOmg?si=gWrSq5bKTZsxh7G6)